const express=require("express")
const app=express()
const cors=require("cors")
const dotenv=require("dotenv")
dotenv.config()
const loanPredictionRoutes=require("./routes/lap.routes")
const userRoutes=require("./routes/user.routes")
const connectDb = require("./util/db")
app.use(cors())
app.use(express.json())
app.use("/api/predict",loanPredictionRoutes)
app.use("/api/auth",userRoutes)
app.get("/",(_,res)=>{
    res.send("EXPRESS SERVER RUNNING SUCCESSFULLY")
})
connectDb()
app.listen(process.env.PORT,"0.0.0.0",()=>console.log("Server running on port:",process.env.PORT))