name: LAP APP
on:
    push:
        branches:
            - main
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Action checkout
              uses: actions/checkout@v3

            - name: Node js setup
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Ec2 Deploy
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.EC2_HOST}}
                username: ubuntu
                key: ${{secrets.EC2_SSH_KEY}}
                script: |
                  cd lap-server
                  git pull origin main
                  npm install
                  pm2 restart all